from pathlib import Path
from typing import Literal
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from ai_sdlc.agents.client import get_llm

PROMPT_FILE = Path(__file__).parent.parent / "prompts" / "security_agent.md"


class Finding(BaseModel):
    severity: Literal["HIGH", "MEDIUM", "LOW", "INFO"]
    file: str
    issue: str
    recommendation: str


class SecurityOutput(BaseModel):
    risk_level: Literal["HIGH", "MEDIUM", "LOW"]
    findings: list[Finding]
    summary: str
    approved: bool = Field(description="True if code is safe to commit, False if HIGH severity findings exist")


def run(code_files: dict[str, str]) -> SecurityOutput:
    prompt_template = PROMPT_FILE.read_text(encoding="utf-8")
    llm = get_llm(temperature=0.1)

    code_str = "\n\n".join(
        f"### {path}\n```python\n{code}\n```"
        for path, code in code_files.items()
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", prompt_template),
        ("human", "Review the following code for security issues:\n\n{code}"),
    ])

    chain = prompt | llm.with_structured_output(SecurityOutput)
    return chain.invoke({"code": code_str})


def save(output: SecurityOutput, output_path: Path = Path("reports/security-review.md")) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    findings_md = ""
    for f in output.findings:
        findings_md += f"\n### [{f.severity}] {f.file}\n**Issue:** {f.issue}\n**Recommendation:** {f.recommendation}\n"

    status = "APPROVED" if output.approved else "BLOCKED — HIGH SEVERITY FINDINGS"

    content = f"""# Security Review — Generated by Security Agent

## Status: {status}

**Overall Risk Level:** {output.risk_level}

## Summary

{output.summary}

## Findings
{findings_md if findings_md else '_No findings._'}
"""
    output_path.write_text(content, encoding="utf-8")
    print(f"[Security Agent] Report written to {output_path}")
