"""
Phase 6 — QA Agent
Generates tests/ and produces reports/coverage.md + reports/functional.md
Run: python run_phase6.py
"""

import os
import subprocess
from pathlib import Path


def _load_dotenv() -> None:
    env_file = Path(".env")
    if not env_file.exists():
        return
    for line in env_file.read_text(encoding="utf-8").splitlines():
        if "=" in line and not line.startswith("#"):
            k, v = line.split("=", 1)
            os.environ.setdefault(k.strip(), v.strip())


def _github_token_from_gh() -> str | None:
    try:
        result = subprocess.run(
            ["gh", "auth", "token"], capture_output=True, text=True, check=True
        )
        return result.stdout.strip() or None
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None


_load_dotenv()
if not os.environ.get("GITHUB_TOKEN"):
    token = _github_token_from_gh()
    if token:
        os.environ["GITHUB_TOKEN"] = token

if not os.environ.get("GITHUB_TOKEN"):
    raise EnvironmentError("GITHUB_TOKEN not set. Add it to .env")

from ai_sdlc.agents import qa_agent
from ai_sdlc.validators.syntax_validator import validate_syntax

SPEC_PATH = Path("docs/project/handout.md")
APP_DIR = Path("app")


# QA agent only needs the HTTP contract — schemas + routes.
# Passing all 10 files exceeds the token limit for gpt-4o-mini.
QA_CONTEXT_FILES = [
    "app/models/schemas.py",
    "app/routes/events.py",
    "app/routes/accounts.py",
    "app/core/exceptions.py",
]


def collect_code() -> dict[str, str]:
    result: dict[str, str] = {}
    for rel in QA_CONTEXT_FILES:
        p = Path(rel)
        if p.exists():
            result[rel] = p.read_text(encoding="utf-8")
    return result


def validate_tests() -> tuple[bool, str]:
    errors: list[str] = []
    for py_file in sorted(Path("tests").rglob("*.py")):
        ok, err = validate_syntax(py_file)
        if not ok:
            errors.append(f"Syntax [{py_file}]: {err}")
    return (len(errors) == 0), "\n".join(errors)


def write_functional_report(output: qa_agent.QAOutput) -> None:
    path = Path("reports/functional.md")
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Functional Test Report — Generated by QA Agent\n", f"{output.summary}\n\n## Test Files\n"]
    for tf in output.test_files:
        lines.append(f"### {tf.file_path}\n{tf.description}\n")
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[QA Agent] Functional report written to {path}")


def main() -> None:
    if not APP_DIR.exists():
        raise FileNotFoundError("app/ directory not found. Run Phase 4 first.")

    spec = SPEC_PATH.read_text(encoding="utf-8")
    code = collect_code()

    # Truncate spec to first 1500 chars — test requirements are in the prompt.
    spec_summary = spec[:1500]

    print(f"[Phase 6] QA Agent generating tests for {len(code)} files...")
    output = qa_agent.run(code, spec_summary)
    qa_agent.save(output)

    ok, err = validate_tests()
    if not ok:
        print(f"\n[Phase 6] Syntax errors in generated tests:\n{err}")
        raise SystemExit(1)

    print(f"\n[Phase 6] Running tests...")
    passed, _ = qa_agent.run_tests_and_report()
    write_functional_report(output)

    print(f"\n[Phase 6] Done.")
    print(f"  Tests passed : {passed}")
    print(f"  Summary      : {output.summary}")
    print(f"  Reports      : reports/coverage.md, reports/functional.md")

    if not passed:
        print("\n  WARNING: some tests failed — review reports/coverage.md")


if __name__ == "__main__":
    main()
