from pathlib import Path
from typing import Optional
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from agents.client import get_llm


class Component(BaseModel):
    name: str
    responsibility: str
    file_path: str


class ArchitectureOutput(BaseModel):
    summary: str = Field(description="2-3 sentence summary of the system design")
    mermaid_diagram: str = Field(description="Full Mermaid diagram string, starting with 'graph TD' or 'flowchart TD'")
    components: list[Component] = Field(description="Each major component in the system")
    design_decisions: list[str] = Field(description="Key decisions made and why")
    data_flow: str = Field(description="Step-by-step description of how a POST /events request flows through the system")


PROMPT_FILE = Path(__file__).parent.parent / ".prompts" / "design_agent.md"


def run(spec_content: str) -> ArchitectureOutput:
    prompt_template = PROMPT_FILE.read_text(encoding="utf-8")
    llm = get_llm(temperature=0.1)

    prompt = ChatPromptTemplate.from_messages([
        ("system", prompt_template),
        ("human", "Here is the full specification:\n\n{spec}"),
    ])

    chain = prompt | llm.with_structured_output(ArchitectureOutput)
    return chain.invoke({"spec": spec_content})


def save(output: ArchitectureOutput, output_path: Path = Path("docs/architecture.md")) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    components_table = "\n".join(
        f"| `{c.file_path}` | {c.name} | {c.responsibility} |"
        for c in output.components
    )

    decisions_list = "\n".join(f"- {d}" for d in output.design_decisions)

    content = f"""# Architecture — Generated by Design Agent

## Summary

{output.summary}

## System Diagram

```mermaid
{output.mermaid_diagram}
```

## Components

| File | Component | Responsibility |
|---|---|---|
{components_table}

## Design Decisions

{decisions_list}

## Data Flow

{output.data_flow}
"""
    output_path.write_text(content, encoding="utf-8")
    print(f"[Design Agent] Architecture written to {output_path}")
