from pathlib import Path
from pydantic import BaseModel, Field
from langchain_core.prompts import ChatPromptTemplate
from agents.client import get_llm
import subprocess

PROMPT_FILE = Path(".prompts/qa_agent.md")


class TestFile(BaseModel):
    file_path: str
    content: str = Field(description="Complete pytest test file — no placeholders, all tests runnable")
    description: str


class QAOutput(BaseModel):
    test_files: list[TestFile]
    conftest_content: str = Field(description="Complete tests/conftest.py with fixtures")
    summary: str


def run(code_files: dict[str, str], spec_content: str) -> QAOutput:
    prompt_template = PROMPT_FILE.read_text(encoding="utf-8")
    llm = get_llm(temperature=0.05)

    code_str = "\n\n".join(
        f"### {path}\n```python\n{code}\n```"
        for path, code in code_files.items()
    )

    prompt = ChatPromptTemplate.from_messages([
        ("system", prompt_template),
        ("human", (
            "Specification:\n{spec}\n\n"
            "Application code to test:\n{code}\n\n"
            "Generate complete, runnable pytest test files covering: "
            "idempotency, out-of-order tolerance, balance computation, and validation."
        )),
    ])

    chain = prompt | llm.with_structured_output(QAOutput)
    return chain.invoke({"spec": spec_content, "code": code_str})


def save(output: QAOutput) -> list[Path]:
    saved: list[Path] = []

    conftest = Path("tests/conftest.py")
    conftest.parent.mkdir(parents=True, exist_ok=True)
    conftest.write_text(output.conftest_content, encoding="utf-8")
    saved.append(conftest)

    for tf in output.test_files:
        path = Path(tf.file_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(tf.content, encoding="utf-8")
        saved.append(path)
        print(f"[QA Agent] Written: {path}")

    return saved


def run_tests_and_report(output_path: Path = Path("reports/coverage.md")) -> tuple[bool, str]:
    output_path.parent.mkdir(parents=True, exist_ok=True)

    result = subprocess.run(
        ["python", "-m", "pytest", "tests/", "--cov=app", "--cov-report=term-missing", "-v"],
        capture_output=True,
        text=True,
    )

    passed = result.returncode == 0
    full_output = result.stdout + result.stderr

    content = f"""# Test Coverage Report — Generated by QA Agent

## Status: {"PASSED" if passed else "FAILED"}

```
{full_output}
```
"""
    output_path.write_text(content, encoding="utf-8")
    print(f"[QA Agent] Coverage report written to {output_path}")
    return passed, full_output
